### ISSUE TITLE
Microservices Not Working

### ISSUE THREAD

**Issue by stephenpaul2727** [airavata-courses/haphulwa#2]
Hi Harsha,

I am unable to run the microservices that you wrote for the project.  I will be linking images of the errors that I have got down. Please refer to them and let me know if there is a problem or if there are any changes. 
**PHP Microservice**
https://pastebin.com/LY4rwz3n

**Java Microservice**
Server: https://pastebin.com/wPdb5Pk4
Client: https://pastebin.com/BfAWnXRF

**Python Microservice**
python AdditionPyClient.py 
Error: 
**No handlers could be found for logger "thrift.transport.TSocket"
Connection Error**

I think the packages are not getting imported while running the programs. Let me know if there is a fix.

**Comment by harsha161992** [comment]
Hi Stephen,

I am updating the code on my local machine.

I should be able to push the final code on GitHub by tonight :)

*Thanks & Regards,*
*Harsha Phulwani*

**Comment by harsha161992** [comment]
Hey,

I just pushed the updated code. You can check now :)

*Thanks & Regards,*
*Harsha Phulwani*

**Comment by stephenpaul2727** [comment]
Hi,

Services are running great. But few components required for this assignment are missing. A client which receives data from all the micro services and the interaction between micro services. But the rest services seems to be working perfectly fine.

**Comment by harsha161992** [comment]
Hey, thanks for the update :)

A quick question.

For the client, I can just have an HTML file which will call the three
microservices, right?

And also can you give me some hints as to how to make microservices
interact? Do I have to use things like RabbitMQ?

Thanks :)


On Sep 4, 2017 12:29 PM, "stephen paul" <notifications@github.com> wrote:

Hi,

Services are running great. But few components required for this assignment
are missing. A client which receives data from all the micro services and
the interaction between micro services. But the rest services seems to be
working perfectly fine.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/airavata-courses/haphulwa/issues/2#issuecomment-326998529>,
or mute the thread

**Comment by stephenpaul2727** [comment]
Harsha ~

yes, a client can be as simple as a jquery client interface (or whichever front-end tech) which uses ajax to send and receive JSON formatted output from your microservices. 

To answer the second question, there is no need to currently use any message passing services. just get contents from the other microservices by pointing to that particular url of microservice and return from another microservice( For Eg. java, node, python are the three microservices you wrote, so try to get contents from java server through node by pointing to the end point exposed by java server).

**Comment by Ameya05** [comment]
Hey, there is no requirement of implementing interaction between
microservices. A simple setup of an UI calling an API server endpoint which
inturn calls your set of microservices is all that is required.
Typically in a microservice architecture, Microservice A does not have
knowledge of Microservice B.

Only the API server knows or has the ability to know where to send requests
to in order to get the task completed.

**Comment by stephenpaul2727** [comment]
Hi Ameya,

Oh, I thought the interaction between micro services is necessary. But I presume Client interface is mandatory though. right? Thanks for the info.

**Comment by Ameya05** [comment]
Yes client interface / UI is required.

**Comment by harsha161992** [comment]
Hey Stephen and Ameya,

Thank you for explaining it to me :)

I pushed the updated code with UI now.

Took me so long because of the CORS thing! Finally, it's over!

*Thanks & Regards,*
*Harsha Phulwani*

**Comment by stephenpaul2727** [comment]
Great, 

I'm closing this issue.
